import Head from 'next/head'
import Banner from '../components/Banner'
import Process from '../components/Process'
import TabMenu from '../components/TabMenu'
import styles from '../styles/Home.module.css'
import { Groups} from '../lib/groups'
import UpcomingLottery from '../components/UpcomingLottery'
import LatestWinners from '../components/LatestWinners'


export default function Home() {
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <TabMenu />
        <Banner />
        <Process groups={Groups}/>
        <UpcomingLottery />
        <LatestWinners />

        
      </main>

      <footer>
       
      </footer>
    </div>
  )
}
